{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/github",
      {
        "assets": [
          { "path": "main.pdf", "label": "Ozeliurs' Updated Resume" }
        ]
      }
    ]
  ],
  "branches": [ "main" ]
}
